export type StudioCapability =
  | 'studio.access'
  | 'studio.intelligence'
  | 'studio.project-state'
  | 'studio.recovery-validator'
  | 'studio.project-twin'
  | 'studio.portfolio-simulator'
  | 'studio.scenario-builder'
  | 'studio.executive-preview'
  | 'studio.ai-preview'
  | 'studio.events'
  | 'studio.performance'
  | 'studio.permissions'
  | 'studio.feature-flags'
  | 'studio.database'
  | 'studio.migrations'
  | 'studio.system-config'
  | 'studio.design-system'

export type StudioRole =
  | 'workspace_admin'
  | 'admin'
  | 'pmo'
  | 'developer'
  | 'portfolio_manager'
  | 'project_owner'
  | 'viewer'
  | 'guest'
  | string
