import { Link } from 'react-router-dom'
import { Plus, Search, MessageSquareText } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useProjectStore } from '@/store/project'
import { useRFIs } from '../hooks/useRFIs'
import RFIStatusBadge from '../components/RFIStatusBadge'
export default function RFIRegisterPage(){
 const projectId=useProjectStore(s=>s.projectId); const [search,setSearch]=useState(''); const {data=[],isLoading,error}=useRFIs(projectId)
 const rows=useMemo(()=>data.filter(r=>`${r.reference_no} ${r.title} ${r.discipline}`.toLowerCase().includes(search.toLowerCase())),[data,search])
 if(!projectId)return <div className="panel p-8 text-center text-slate-400">Select a project to view its RFIs.</div>
 return <section className="space-y-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[#c49e48]">Technical coordination</p><h1 className="mt-1 text-2xl font-semibold">RFI Register</h1><p className="mt-1 text-sm text-slate-400">Track questions, responsibility, response time and closure.</p></div><Link to="/app/rfis/new" className="btn-primary inline-flex items-center gap-2"><Plus size={16}/>New RFI</Link></div>
 <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Open',data.filter(r=>!['Closed','Rejected'].includes(r.status)).length],['Overdue',data.filter(r=>r.due_date&&new Date(r.due_date)<new Date()&&!['Answered','Closed'].includes(r.status)).length],['Answered',data.filter(r=>r.status==='Answered').length],['Closed',data.filter(r=>r.status==='Closed').length]].map(([l,v])=><div key={String(l)} className="panel p-4"><div className="text-xs text-slate-500">{l}</div><div className="mt-1 text-2xl font-semibold">{v}</div></div>)}</div>
 <div className="panel overflow-hidden"><div className="border-b border-white/10 p-4"><div className="relative max-w-md"><Search size={16} className="absolute left-3 top-3 text-slate-500"/><input className="form-control pl-9" placeholder="Search RFIs..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
 {isLoading?<div className="p-8 text-slate-400">Loading RFIs…</div>:error?<div className="p-8 text-red-300">{(error as Error).message}</div>:rows.length===0?<div className="p-10 text-center"><MessageSquareText className="mx-auto text-slate-600"/><p className="mt-3 text-slate-400">No RFIs found.</p></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-white/[.03] text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Reference</th><th className="p-4">Title</th><th className="p-4">Discipline</th><th className="p-4">Priority</th><th className="p-4">Due</th><th className="p-4">Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-white/[.06] hover:bg-white/[.025]"><td className="p-4"><Link className="font-medium text-[#c49e48]" to={`/app/rfis/${r.id}`}>{r.reference_no}</Link></td><td className="p-4 text-slate-200">{r.title}</td><td className="p-4 text-slate-400">{r.discipline}</td><td className="p-4 text-slate-400">{r.priority}</td><td className="p-4 text-slate-400">{r.due_date||'—'}</td><td className="p-4"><RFIStatusBadge status={r.status}/></td></tr>)}</tbody></table></div>}</div></section>
}
