
import { FormEvent,useEffect,useMemo,useState } from 'react'
import { ArrowLeft,MessageSquarePlus,ThumbsUp,RefreshCw } from 'lucide-react'
import { useLocation,useNavigate } from 'react-router-dom'
import { useWorkspace } from '@/workspace/WorkspaceProvider'
import { useProjectStore } from '@/store/project'
import { useMembershipStore } from '@/store/membership'
import { listFeedback,submitFeedback,updateFeedback,voteFeedback } from '@/services/productExperienceService'
import type { FeedbackItem,FeedbackCategory,FeedbackPriority } from '@/services/productExperienceTypes'

export default function FeedbackPage(){const navigate=useNavigate();
  const {activeWorkspace}=useWorkspace();const {projectId,projectName}=useProjectStore();const role=useMembershipStore(s=>s.role);const location=useLocation();const workspaceScope=new URLSearchParams(location.search).get('scope')==='workspace';const effectiveProjectId=workspaceScope?null:projectId;const effectiveProjectName=workspaceScope?'Workspace-level':projectName
  const [items,setItems]=useState<FeedbackItem[]>([]);const [show,setShow]=useState(new URLSearchParams(location.search).get('new')==='1');const [message,setMessage]=useState('')
  const admin=['workspace_admin','admin','pmo'].includes(role||'')
  async function load(){if(!activeWorkspace)return;try{setItems(await listFeedback(activeWorkspace.id,!admin))}catch(e){setMessage(e instanceof Error?e.message:'Unable to load feedback.')}}
  useEffect(()=>{void load()},[activeWorkspace?.id,admin])
  const stats=useMemo(()=>({open:items.filter(i=>!['resolved','released','closed'].includes(i.status)).length,review:items.filter(i=>['acknowledged','under_review'].includes(i.status)).length,resolved:items.filter(i=>['resolved','released','closed'].includes(i.status)).length}),[items])
  if(!activeWorkspace)return null
  return <div className="-m-4 min-h-screen bg-[#f6f5f1] p-4 sm:-m-6 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1500px] space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3">
      <button onClick={()=>navigate('/projects')} className="btn btn-ghost"><ArrowLeft size={15}/>Back to Workspace Hub</button>
      <button onClick={()=>navigate('/product-centre')} className="text-xs font-semibold text-[#6f7d89] hover:text-[#173f5f]">Open Product Centre</button>
    </div>
    <section className="rounded-[26px] border bg-white p-7"><div className="flex flex-wrap justify-between gap-4"><div><div className="text-[11px] font-semibold uppercase tracking-[.18em] text-[#df5f41]">Rapid feedback loop</div><h1 className="mt-2 text-3xl font-semibold text-[#102943]">Feedback Centre</h1><p className="mt-2 text-sm text-[#6f7d89]">Report issues, suggest improvements and follow progress in one place.</p></div><div className="flex gap-2"><button onClick={()=>setShow(true)} className="btn btn-gold"><MessageSquarePlus size={15}/>Submit feedback</button><button onClick={()=>void load()} className="btn btn-ghost"><RefreshCw size={15}/>Refresh</button></div></div></section>
    <section className="grid gap-3 md:grid-cols-4"><Metric label="Submitted" value={items.length}/><Metric label="Open" value={stats.open}/><Metric label="Under review" value={stats.review}/><Metric label="Resolved" value={stats.resolved}/></section>
    {message&&<div className="rounded-xl border bg-white p-4 text-sm">{message}</div>}
    <section className="rounded-[24px] border bg-white"><div className="overflow-x-auto"><table className="tbl"><thead><tr><th>ID</th><th>Title</th><th>Category</th><th>Priority</th><th>Status</th><th>Project</th><th>Votes</th>{admin&&<th></th>}</tr></thead><tbody>{items.length?items.map(i=><tr key={i.id}><td>{i.reference}</td><td><div className="font-semibold">{i.title}</div><div className="text-xs text-[#87929b]">{i.module||'General'}</div></td><td>{i.category.replace(/_/g,' ')}</td><td>{i.priority}</td><td><span className="badge badge-muted">{i.status.replace(/_/g,' ')}</span></td><td>{String(i.metadata.projectName||effectiveProjectName||'—')}</td><td><button onClick={async()=>{await voteFeedback(i.id,activeWorkspace.id);await load()}} className="inline-flex items-center gap-1"><ThumbsUp size={13}/>{i.voteCount}</button></td>{admin&&<td><select className="form-control min-w-36" value={i.status} onChange={async e=>{await updateFeedback(i.id,{status:e.target.value});await load()}}>{['submitted','acknowledged','under_review','in_development','testing','resolved','released','closed'].map(v=><option key={v} value={v}>{v.replace(/_/g,' ')}</option>)}</select></td>}</tr>):<tr><td colSpan={8} className="p-12 text-center text-[#87929b]">No feedback submitted yet.</td></tr>}</tbody></table></div></section>
  </div>{show&&<FeedbackDialog workspaceId={activeWorkspace.id} projectId={effectiveProjectId} projectName={effectiveProjectName} pageUrl={location.pathname} onClose={()=>setShow(false)} onSaved={async (item:FeedbackItem)=>{setShow(false);setMessage(`Thank you. Feedback ID ${item.reference} has been submitted.`);await load()}}/>}</div>
}
function FeedbackDialog({workspaceId,projectId,projectName,pageUrl,onClose,onSaved}:any){const [form,setForm]=useState({title:'',description:'',category:'bug' as FeedbackCategory,priority:'medium' as FeedbackPriority,module:pageUrl.split('/').pop()||'general'});const [saving,setSaving]=useState(false);async function submit(e:FormEvent){e.preventDefault();setSaving(true);try{const item=await submitFeedback({workspace_id:workspaceId,project_id:projectId?String(projectId):null,title:form.title,description:form.description,category:form.category,priority:form.priority,status:'submitted',module:form.module,page_url:pageUrl,metadata:{projectName,appVersion:import.meta.env.VITE_APP_VERSION||'1.0.0'}});await onSaved(item)}finally{setSaving(false)}}return <div className="fixed inset-0 z-50 bg-[#102943]/35" onClick={onClose}><aside className="ml-auto h-full w-full max-w-lg bg-white p-6" onClick={e=>e.stopPropagation()}><h2 className="text-2xl font-semibold">Submit feedback</h2><form onSubmit={submit} className="mt-6 space-y-4"><Field label="Title"><input className="form-control" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Category"><select className="form-control" value={form.category} onChange={e=>setForm({...form,category:e.target.value as FeedbackCategory})}>{['bug','feature_request','improvement','question','performance','ui_ux','permission','data','other'].map(v=><option key={v} value={v}>{v.replace(/_/g,' ')}</option>)}</select></Field><Field label="Priority"><select className="form-control" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as FeedbackPriority})}>{['critical','high','medium','low'].map(v=><option key={v}>{v}</option>)}</select></Field></div><Field label="Description"><textarea className="form-control min-h-40" required placeholder="What happened? What were you trying to do? What did you expect?" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="rounded-xl bg-[#f5f8fa] p-3 text-xs text-[#6f7d89]">Page, project, browser, screen size, time zone and app version will be attached automatically.</div><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="btn btn-ghost">Cancel</button><button className="btn btn-gold" disabled={saving}>{saving?'Submitting…':'Submit feedback'}</button></div></form></aside></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border bg-white p-5"><div className="text-3xl font-semibold text-[#102943]">{value}</div><div className="mt-2 text-xs font-semibold text-[#536170]">{label}</div></div>}
function Field({label,children}:{label:string;children:any}){return <label className="block text-xs font-semibold text-[#52616d]">{label}<div className="mt-2">{children}</div></label>}
