
import { useEffect,useMemo,useState } from 'react'
import { BookOpen,Search,PlayCircle,LifeBuoy,MessageSquarePlus } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useWorkspace } from '@/workspace/WorkspaceProvider'
import { listHelpArticles,recordHelpSearch } from '@/services/productExperienceService'
import type { HelpArticle } from '@/services/productExperienceTypes'
export default function HelpPage(){const {activeWorkspace}=useWorkspace();const nav=useNavigate();const [articles,setArticles]=useState<HelpArticle[]>([]);const [q,setQ]=useState('');const [selected,setSelected]=useState<HelpArticle|null>(null)
useEffect(()=>{if(activeWorkspace)listHelpArticles(activeWorkspace.id).then(setArticles)},[activeWorkspace?.id])
const filtered=useMemo(()=>articles.filter(a=>`${a.title} ${a.summary} ${a.body} ${a.category}`.toLowerCase().includes(q.toLowerCase())),[articles,q])
useEffect(()=>{if(activeWorkspace&&q.trim().length>2){const t=setTimeout(()=>void recordHelpSearch(activeWorkspace.id,q,filtered.length),600);return()=>clearTimeout(t)}},[q,filtered.length,activeWorkspace?.id])
return <div className="-m-4 min-h-screen bg-[#f6f5f1] p-4 sm:-m-6 sm:p-6 lg:p-8"><div className="mx-auto max-w-[1400px] space-y-5"><section className="rounded-[26px] border bg-[#173f5f] p-8 text-white"><div className="text-xs uppercase tracking-[.18em] text-white/50">Help Centre</div><h1 className="mt-2 text-4xl font-semibold">How can we help?</h1><div className="relative mt-6 max-w-3xl"><Search className="absolute left-4 top-1/2 -translate-y-1/2" size={18}/><input className="w-full rounded-2xl bg-white px-12 py-4 text-[#173f5f]" placeholder="Search anything..." value={q} onChange={e=>setQ(e.target.value)}/></div></section>
<section className="grid gap-4 md:grid-cols-3"><Quick icon={BookOpen} title="Quick Start" text="Create a workspace, portfolio, project and upload a schedule."/><Quick icon={PlayCircle} title="Interactive Guides" text="Step-by-step guidance for core SiteFlow PM workflows."/><button onClick={()=>nav('/app/feedback?new=1')} className="text-left"><Quick icon={MessageSquarePlus} title="Contact Support" text="Report an issue or ask the PMO team for help."/></button></section>
<section className="grid gap-5 lg:grid-cols-[320px_1fr]"><div className="rounded-[24px] border bg-white p-5"><h2 className="font-semibold">Knowledge Base</h2><div className="mt-4 space-y-2">{filtered.map(a=><button key={a.id} onClick={()=>setSelected(a)} className="w-full rounded-xl border p-3 text-left hover:bg-[#f7f9fa]"><div className="text-xs text-[#87929b]">{a.category}</div><div className="mt-1 font-semibold">{a.title}</div><div className="mt-1 text-xs text-[#6f7d89]">{a.summary}</div></button>)}</div></div><article className="rounded-[24px] border bg-white p-7">{selected?<><div className="text-xs uppercase tracking-wider text-[#df5f41]">{selected.category}</div><h2 className="mt-2 text-3xl font-semibold text-[#102943]">{selected.title}</h2><div className="mt-6 whitespace-pre-wrap text-sm leading-7 text-[#536170]">{selected.body}</div></>:<div className="grid min-h-80 place-items-center text-center"><div><LifeBuoy className="mx-auto text-[#8aa0ad]"/><h2 className="mt-3 text-xl font-semibold">Select an article</h2><p className="mt-2 text-sm text-[#87929b]">Browse the knowledge base or search for a workflow.</p></div></div>}</article></section></div></div>}
function Quick({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="h-full rounded-2xl border bg-white p-5"><Icon className="text-[#1f668f]"/><h3 className="mt-4 font-semibold text-[#102943]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#6f7d89]">{text}</p></div>}
